name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
        cd DogAPI
        dotnet restore
    - name: Build
      run: |
        cd DogAPI
        dotnet build
    - name: Test
      run: |
        cd DogAPI
        dotnet test --no-build --verbosity normal
    - name: Publish
      run: |
        cd DogAPI
        dotnet publish -c Release -o website
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: DogAPI/website
        if-no-files-found: error
